name: GitHub Action flow to ghcr.io with inline cache

on:
  workflow_dispatch:

jobs:
  build-push-images-with-inline-cache:
    name: Build and push Docker image to ghcr.io
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Buildx set-up
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/x86_64,linux/arm64
          push: true
          cache-from: type=registry,ref=ghcr.io/icheredn/lab10:extended
          cache-to: type=inline
          tags: |
            ghcr.io/icheredn/lab10:extended
      
